/**
 * V100 Issue #39: Icon/button cache generator (Node.js version).
 *
 * Renders every Gaffer icon to a standalone .svg file in
 * public/icons/gaffer/ using react-dom/server. This is the proper way
 * to export React SVG components to static assets — the Python script
 * in the same folder (export_gaffer_icons.py) is a fallback that uses
 * regex parsing and can't handle JSX expressions.
 *
 * Usage:
 *   node scripts/export_gaffer_icons.mjs
 *
 * Output: public/icons/gaffer/<IconName>.svg (one file per icon)
 *
 * Each SVG is rendered with default props (size=24, brassColor=#c9972e)
 * — for variant renders, use the React component directly.
 */

import { renderToStaticMarkup } from "react-dom/server";
import { createElement } from "react";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

import * as Icons from "../src/components/ui/icons/GafferIcons.tsx";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUT_DIR = join(REPO_ROOT, "public", "icons", "gaffer");

// Default render props — match GafferIcon defaults
const DEFAULT_PROPS = { size: 24, brassColor: "#c9972e" };

function main() {
  const iconNames = Object.keys(Icons).filter(
    (name) =>
      name.endsWith("Icon") &&
      !name.startsWith("ATTRIBUTE_") &&
      typeof Icons[name] === "function",
  );

  console.log(`Found ${iconNames.length} icons in GafferIcons.tsx`);

  mkdirSync(OUTPUT_DIR, { recursive: true });
  let succeeded = 0;
  let failed = 0;

  for (const name of iconNames) {
    const Component = Icons[name];
    try {
      const element = createElement(Component, DEFAULT_PROPS);
      const svgMarkup = renderToStaticMarkup(element);

      // Wrap with XML declaration + header comment
      const header = `<!--
  Gaffer Icon: ${name}
  Auto-generated by scripts/export_gaffer_icons.mjs
  Source: src/components/ui/icons/GafferIcons.tsx
  DO NOT EDIT — edit the source .tsx and re-run the script.
-->
`;
      const content = header + svgMarkup + "\n";
      writeFileSync(join(OUTPUT_DIR, `${name}.svg`), content, "utf-8");
      succeeded++;
    } catch (err) {
      console.error(`  FAIL ${name}: ${err.message}`);
      failed++;
    }
  }

  console.log(`\nResults:`);
  console.log(`  Succeeded: ${succeeded}/${iconNames.length}`);
  console.log(`  Failed: ${failed}`);
  console.log(`\nOutput: ${OUTPUT_DIR}`);
}

main();
