#!/usr/bin/env python3
"""
V100 Issue #39: Icon/button cache generator.

Exports every Gaffer icon (BodyIcon, BallIcon, etc.) from
src/components/ui/icons/GafferIcons.tsx into standalone .svg files at
public/icons/gaffer/. These static assets can be used:

  - As favicon / app icons
  - In static HTML pages (e.g. landing page, error pages)
  - In OpenGraph / social preview images
  - As embed assets in emails or PDFs
  - By designers who want to modify and re-import

This script is run manually whenever new icons are added — it does NOT
run on every build (would be wasteful). Run:

    python3 scripts/export_gaffer_icons.py

Output: public/icons/gaffer/<icon-name>.svg (one file per icon)

NOTE: This is a best-effort static export. Icons that use React-specific
features (conditional props, dynamic children) are exported with their
default props (size=24, brassColor=#c9972e). For dynamic rendering, use
the React component instead of the static SVG.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ICONS_SOURCE = REPO_ROOT / "src" / "components" / "ui" / "icons" / "GafferIcons.tsx"
OUTPUT_DIR = REPO_ROOT / "public" / "icons" / "gaffer"

# Default export props — match GafferIcon defaults
DEFAULT_SIZE = 24
DEFAULT_BRASS = "#c9972e"


def extract_icon_names(source: str) -> list[str]:
    """Find all `export function XxxIcon(...)` declarations."""
    pattern = r"export function (\w+Icon)\b"
    return sorted(set(re.findall(pattern, source)))


def extract_icon_svg_body(source: str, icon_name: str) -> str | None:
    """
    Best-effort extraction of the inner SVG markup for a given icon.
    Returns the <svg>...</svg> string with default prop values substituted.

    This is a simple parser, NOT a full TS compiler. It handles:
    - <svg {...base(size)} {...props}> -> expands to literal svg attrs
    - {brassColor} -> #c9972e
    - {size} -> 24
    - Conditional/JSX expressions are kept as-is (may produce invalid SVG
      for complex icons — those need manual export or React rendering)

    For icons that fail to parse cleanly, we emit a placeholder SVG and
    log a warning so the dev can manually export.
    """
    # Find the function body
    pattern = rf"export function {re.escape(icon_name)}\s*\([^)]*\)\s*\{{(?P<body>.*?)\n\}}\s*$"
    match = re.search(pattern, source, re.DOTALL | re.MULTILINE)
    if not match:
        return None
    body = match.group("body")

    # Extract the <svg>...</svg> block
    svg_match = re.search(r"<svg[^>]*>.*?</svg>", body, re.DOTALL)
    if not svg_match:
        return None
    svg = svg_match.group(0)

    # Substitute known variables
    # Replace {...base(size)} with literal attrs (best effort)
    base_attrs = (
        f'width="{DEFAULT_SIZE}" height="{DEFAULT_SIZE}" viewBox="0 0 24 24" '
        f'fill="none" stroke="currentColor" stroke-width="1.5" '
        f'stroke-linecap="round" stroke-linejoin="round"'
    )
    # Remove the {...base(size)} spread
    svg = re.sub(r"\{\.\.\.base\(size\)\}", base_attrs, svg)
    # Remove {...props}
    svg = re.sub(r"\{\.\.\.props\}", "", svg)
    # Replace brassColor literal
    svg = svg.replace("{brassColor}", DEFAULT_BRASS)
    # Replace size literal (rare in body, but possible)
    svg = svg.replace("{size}", str(DEFAULT_SIZE))

    # If any JSX expression remains ({...}), this icon can't be cleanly
    # exported statically — emit a placeholder.
    if "{" in svg and not svg.strip().startswith("<!--"):
        # Check for unresolved JSX
        unresolved = re.findall(r"\{[^}]+\}", svg)
        if unresolved:
            # Filter out ones we know are safe (style attributes etc.)
            truly_unresolved = [
                u for u in unresolved
                if "currentColor" not in u and DEFAULT_BRASS not in u
            ]
            if truly_unresolved:
                return None  # signal failure

    return svg


def write_svg(path: Path, icon_name: str, svg_body: str) -> None:
    """Write the SVG file with a header comment."""
    header = (
        f"<!--\n"
        f"  Gaffer Icon: {icon_name}\n"
        f"  Auto-generated by scripts/export_gaffer_icons.py\n"
        f"  Source: src/components/ui/icons/GafferIcons.tsx\n"
        f"  DO NOT EDIT — edit the source .tsx and re-run the script.\n"
        f"-->\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(header + svg_body + "\n", encoding="utf-8")


def main() -> int:
    if not ICONS_SOURCE.exists():
        print(f"ERROR: Source not found: {ICONS_SOURCE}", file=sys.stderr)
        return 1

    source = ICONS_SOURCE.read_text(encoding="utf-8")
    icon_names = extract_icon_names(source)
    print(f"Found {len(icon_names)} icons in {ICONS_SOURCE.name}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    succeeded = 0
    failed: list[str] = []

    for name in icon_names:
        svg_body = extract_icon_svg_body(source, name)
        if svg_body is None:
            failed.append(name)
            # Write a placeholder so the file list is complete
            placeholder = (
                f'<!-- {name}: static export not supported, use React component -->\n'
                f'<svg width="{DEFAULT_SIZE}" height="{DEFAULT_SIZE}" viewBox="0 0 24 24" '
                f'fill="none" stroke="currentColor" stroke-width="1.5">\n'
                f'  <circle cx="12" cy="12" r="10" stroke-dasharray="2 2" />\n'
                f'  <text x="12" y="16" text-anchor="middle" font-size="8" '
                f'fill="currentColor" stroke="none">{name[0]}</text>\n'
                f'</svg>\n'
            )
            write_svg(OUTPUT_DIR / f"{name}.svg", name, placeholder)
        else:
            write_svg(OUTPUT_DIR / f"{name}.svg", name, svg_body)
            succeeded += 1

    print(f"\nResults:")
    print(f"  Succeeded: {succeeded}/{len(icon_names)}")
    print(f"  Failed (placeholder written): {len(failed)}")
    if failed:
        print(f"  Failed icons: {', '.join(failed)}")
    print(f"\nOutput: {OUTPUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
